AppBundle\Entity\Patch:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\PatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        channel:
            type: integer
        intensity:
            type: integer
        type:
            type: string
            length: '3'
        eventName:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
