sudo: required

language: c

compiler:
- clang
- gcc

services:
- docker

before_install:
- docker build -t louisleblin/champylight .

script:
- docker run louisleblin/champylight /bin/sh -c "make -C /app/build cxxtest"

# Publish on DockerHub
deploy:
  provider: script
  script: ./scripts/docker_push
  on:
    branch: master

notifications:
  email: false
  slack: champylight:m0KaztICbNRSLHf2wrNLapEy
